In [10]:
import pandas as pd

In [11]:
df = pd.read_csv("datasets/online_retail_rfm_working_data.csv")

In [12]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Total
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085,United Kingdom,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom,30.0

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 407695 entries, 0 to 407694
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      407695 non-null  int64
 1   StockCode    407695 non-null  object
 2   Description  407695 non-null  object
 3   Quantity     407695 non-null  int64
 4   InvoiceDate  407695 non-null  object
 5   Price        407695 non-null  float64
 6   Customer ID  407695 non-null  int64
 7   Country      407695 non-null  object
 8   Total        407695 non-null  float64
dtypes: float64(2), int64(3), object(4)
memory usage: 28.0+ MB

In [14]:
df.describe()

,Invoice,Quantity,Price,Customer ID,Total
count,407695.000000,407695.000000,407695.000000,407695.000000,407695.000000
mean,514760.707239,13.586686,3.294188,15368.504107,21.663261
std,14101.015474,96.842229,34.756655,1679.795700,77.147356
min,489434.000000,1.000000,0.000000,12346.000000,0.000000
25%,502764.000000,2.000000,1.250000,13997.000000,4.950000
50%,515303.000000,5.000000,1.950000,15321.000000,11.900000
75%,527104.000000,12.000000,3.750000,16812.000000,19.500000
max,538171.000000,19152.000000,10953.500000,18287.000000,15818.400000

In [16]:
df["Customer ID"].nunique()

4314

In [20]:
df[df["Price"] == 0]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Total
3631,489825,22076,6 RIBBONS EMPIRE,12,2009-12-02 13:34:00,0.0,16126,United Kingdom,0.0
4754,489998,48185,DOOR MAT FAIRY CAKE,2,2009-12-03 11:19:00,0.0,15658,United Kingdom,0.0
12751,490727,M,Manual,1,2009-12-07 16:38:00,0.0,17231,United Kingdom,0.0
14138,490961,22065,CHRISTMAS PUDDING TRINKET POT,1,2009-12-08 15:25:00,0.0,14108,United Kingdom,0.0
14139,490961,22142,CHRISTMAS CRAFT WHITE FAIRY,12,2009-12-08 15:25:00,0.0,14108,United Kingdom,0.0
23777,492079,85042,ANTIQUE LILY FAIRY LIGHTS,8,2009-12-15 13:49:00,0.0,15070,United Kingdom,0.0
28679,492760,21143,ANTIQUE GLASS HEART DECORATION,12,2009-12-18 14:22:00,0.0,18071,United Kingdom,0.0
32556,493761,79320,FLAMINGO LIGHTS,24,2010-01-06 14:54:00,0.0,14258,United Kingdom,0.0
33679,493899,22355,"CHARLOTTE BAG , SUKI DESIGN",10,2010-01-08 10:43:00,0.0,12417,Belgium,0.0
38402,494607,21533,RETRO SPOT LARGE MILK JUG,12,2010-01-15 12:43:00,0.0,16858,United Kingdom,0.0
62029,497819,TEST001,This is a test product.,5,2010-02-12 14:58:00,0.0,14103,United Kingdom,0.0
62119,497843,TEST001,This is a test product.,5,2010-02-12 15:47:00,0.0,14827,United Kingdom,0.0
80004,500073,21662,VINTAGE GLASS COFFEE CADDY,1,2010-03-04 11:44:00,0.0,13047,United Kingdom,0.0
109463,503585,22459,CAST IRON HOOK GARDEN TROWEL,8,2010-04-01 17:13:00,0.0,13047,United Kingdom,0.0
109464,503585,22458,CAST IRON HOOK GARDEN FORK,8,2010-04-01 17:13:00,0.0,13047,United Kingdom,0.0
122840,505083,22376,AIRLINE BAG VINTAGE JET SET WHITE,1,2010-04-20 09:56:00,0.0,12623,Germany,0.0
176096,511902,21765,HANGING METAL BIRD BATH,1,2010-06-11 11:12:00,0.0,12748,United Kingdom,0.0
182620,512609,20914,SET/5 RED SPOTTY LID GLASS BOWLS,2,2010-06-17 10:12:00,0.0,14045,United Kingdom,0.0
188739,513416,22423,REGENCY CAKESTAND 3 TIER,5,2010-06-24 12:34:00,0.0,13089,United Kingdom,0.0
211234,516304,22690,DOORMAT HOME SWEET HOME BLUE,6,2010-07-19 13:13:00,0.0,14025,United Kingdom,0.0
227125,518231,22472,TV DINNER TRAY DOLLY GIRL,9,2010-08-05 15:28:00,0.0,12471,Germany,0.0
251706,521375,22202,MILK PAN PINK RETROSPOT,3,2010-09-05 11:58:00,0.0,12647,Germany,0.0
277735,524181,46000M,POLYESTER FILLER PAD 45x45cm,648,2010-09-27 16:59:00,0.0,17450,United Kingdom,0.0
282126,524701,22218,CAKE STAND LACE WHITE,2,2010-09-30 12:19:00,0.0,17667,United Kingdom,0.0
305396,527084,22630,DOLLY GIRL LUNCH BOX,64,2010-10-14 15:33:00,0.0,14646,Netherlands,0.0
312226,527696,22121,NOEL WOODEN BLOCK LETTERS,1,2010-10-18 15:13:00,0.0,13554,United Kingdom,0.0
344271,531361,21843,RED RETROSPOT CAKE STAND,2,2010-11-07 14:26:00,0.0,12820,United Kingdom,0.0
355454,532470,22624,IVORY KITCHEN SCALES,2,2010-11-12 11:41:00,0.0,12647,Germany,0.0
368948,533822,22846,BREAD BIN DINER STYLE RED,1,2010-11-19 09:40:00,0.0,12647,Germany,0.0
368949,533822,22845,VINTAGE CREAM CAT FOOD CONTAINER,1,2010-11-19 09:40:00,0.0,12647,Germany,0.0
400104,537197,22841,ROUND CAKE TIN VINTAGE GREEN,1,2010-12-05 14:02:00,0.0,12647,Germany,0.0

In [22]:
df.nlargest(10, "Quantity")
df.nlargest(10, "Price")

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Total
98328,502263,M,Manual,1,2010-03-23 15:22:00,10953.50,12918,United Kingdom,10953.50
277564,524159,M,Manual,1,2010-09-27 16:12:00,10468.80,14063,United Kingdom,10468.80
50564,496115,M,Manual,1,2010-01-29 11:04:00,8985.60,17949,United Kingdom,8985.60
94134,501766,M,Manual,1,2010-03-19 11:35:00,6958.17,15760,Norway,6958.17
94218,501768,M,Manual,1,2010-03-19 11:45:00,6958.17,15760,Norway,6958.17
220794,517483,M,Manual,1,2010-07-29 12:29:00,3610.50,12737,France,3610.50
277594,524162,M,Manual,1,2010-09-27 16:18:00,2769.90,14063,United Kingdom,2769.90
327929,529356,M,Manual,1,2010-10-28 09:44:00,2736.16,14156,EIRE,2736.16
306997,527258,M,Manual,1,2010-10-15 12:40:00,2667.88,15202,United Kingdom,2667.88
290709,525498,M,Manual,1,2010-10-05 16:47:00,2545.85,14156,EIRE,2545.85

In [37]:
(df["StockCode"] == 'M').sum()

np.int64(426)

In [41]:
df[df["StockCode"] == 'M']['Total'].max()

10953.5

In [49]:
M_revenue = df.loc[df["StockCode"] == 'M', "Total"].sum()
M_revenue

np.float64(98560.63999999998)

In [48]:
total_revenue = df["Total"].sum()
total_revenue

np.float64(8832003.274000002)

In [47]:
M_revenue/total_revenue

np.float64(0.011159488616829057)

In [54]:
df.loc[df["StockCode"] == "M", "Description"].unique()

array(['Manual'], dtype=object)

In [55]:
df.columns

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country', 'Total'],
      dtype='object')

In [64]:
df.loc[
    df["StockCode"].str.match(r"^[A-Za-z]", na=False),
    ["Total"]
    ].sum()
# ].groupby("StockCode")["Total"].sum()

Total    158619.944
dtype: float64

In [67]:
df.columns

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country', 'Total'],
      dtype='object')

In [92]:
df.info()
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 407695 entries, 0 to 407694
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      407695 non-null  int64
 1   StockCode    407695 non-null  object
 2   Description  407695 non-null  object
 3   Quantity     407695 non-null  int64
 4   InvoiceDate  407695 non-null  datetime64[ns]
 5   Price        407695 non-null  float64
 6   Customer ID  407695 non-null  int64
 7   Country      407695 non-null  object
 8   Total        407695 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(3), object(3)
memory usage: 28.0+ MB

### RECENCY

In [94]:
latest_date = df["InvoiceDate"].max()

In [95]:
customer_latest = df.groupby("Customer ID")["InvoiceDate"].max()
last_purchase = latest_date - customer_latest

In [101]:
last_purchase.max()

Timedelta('373 days 10:06:00')